# Generated by Django 3.0.5 on 2020-06-13 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0012_auto_20200527_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
                ('security_type', models.CharField(choices=[('pif_rshb', 'ОПИФ РСХБ'), ('bpif', 'БПИФ'), ('stock', 'Акция'), ('bond', 'Облигация')], default='bond', max_length=20)),
                ('parce_url', models.URLField(blank=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('shortname', models.CharField(blank=True, max_length=30)),
                ('regnumber', models.CharField(blank=True, max_length=30)),
                ('secid', models.CharField(blank=True, max_length=30)),
                ('isin', models.CharField(blank=True, max_length=30)),
                ('emitent', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('last_update', models.DateTimeField()),
                ('oldest_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('buy', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('count', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_securities', to='portfolio.InvestmentPortfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='moex.Security')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityPortfolios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('today_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='portfolio.InvestmentPortfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='moex.Security')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percent_prev_date', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='moex.Security')),
            ],
        ),
    ]
