# Generated by Django 3.0.5 on 2020-06-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='last_update',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='oldest_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
