# Generated by Django 3.0.5 on 2020-06-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0002_auto_20200613_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='fullname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
