# Generated by Django 3.0.5 on 2020-06-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0005_auto_20200613_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='today_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
