# Generated by Django 3.0.5 on 2020-06-14 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moex', '0006_security_today_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='users_follows',
            field=models.ManyToManyField(blank=True, related_name='security_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
