# Generated by Django 3.0.5 on 2020-06-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0007_security_users_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='oldest_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='securityhistory',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='date',
            field=models.DateField(),
        ),
    ]
