# Generated by Django 3.0.5 on 2020-06-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0008_auto_20200615_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityhistory',
            options={'ordering': ['-date']},
        ),
    ]
