# Generated by Django 3.0.5 on 2020-07-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0010_auto_20200626_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='board',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='security',
            name='engine',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='security',
            name='facevalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='security',
            name='initialfacevalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='security',
            name='market',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='security',
            name='matdate',
            field=models.DateField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='security',
            name='security_type',
            field=models.CharField(choices=[('pif_rshb', 'ОПИФ РСХБ'), ('ppif', 'БПИФ'), ('share', 'Акция'), ('bond', 'Облигация')], default='bond', max_length=20),
        ),
    ]
