# Generated by Django 3.0.5 on 2020-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0011_auto_20200704_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='matdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
