# Generated by Django 3.0.5 on 2020-07-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0019_auto_20200705_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='security',
            options={'ordering': ['-last_update']},
        ),
        migrations.AlterField(
            model_name='security',
            name='couponpercent',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='couponvalue',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='facevalue',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='security',
            name='initialfacevalue',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='security',
            name='today_price',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='securityhistory',
            name='price',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='securityportfolios',
            name='today_price',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='commission',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=17),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='price',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=17),
        ),
    ]
