# Generated by Django 3.0.5 on 2020-07-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0020_auto_20200706_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='security_type',
            field=models.CharField(choices=[('pif_rshb', 'ОПИФ РСХБ'), ('ppif', 'БПИФ'), ('share', 'Акция'), ('bond', 'Облигация'), ('futures', 'Фьючерс')], default='bond', max_length=20),
        ),
    ]
