# Generated by Django 3.0.5 on 2020-07-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0021_auto_20200708_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='nkd',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
