# Generated by Django 3.0.5 on 2020-07-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0022_tradehistory_nkd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityportfolios',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='tradehistory',
            options={'ordering': ['-date']},
        ),
    ]
