# Generated by Django 3.0.5 on 2020-07-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0023_auto_20200716_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='ndfl',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
