# Generated by Django 3.0.5 on 2020-07-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0024_tradehistory_ndfl'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityportfolios',
            name='total_cost',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=17),
        ),
    ]
