# Generated by Django 3.0.5 on 2020-07-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0025_securityportfolios_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='accint',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='security',
            name='faceunit',
            field=models.CharField(blank=True, choices=[('SUR', 'РУБ'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CNY', 'CNY')], default='SUR', max_length=20),
        ),
    ]
