# Generated by Django 3.0.5 on 2020-08-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0027_security_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='change_price_percent',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
