# Generated by Django 3.0.5 on 2020-08-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0028_security_change_price_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='security_type',
            field=models.CharField(choices=[('pif_rshb', 'ОПИФ РСХБ'), ('ppif', 'БПИФ'), ('share', 'Акция'), ('bond', 'Облигация'), ('futures', 'Фьючерс'), ('index', 'Индекс'), ('etf_ppif', 'ETF')], default='bond', max_length=20),
        ),
    ]
