# Generated by Django 3.0.7 on 2020-11-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0030_auto_20201007_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='main_board_faceunit',
            field=models.CharField(blank=True, choices=[('SUR', 'РУБ'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CNY', 'CNY')], default='SUR', max_length=20, null=True),
        ),
    ]
