# Generated by Django 3.0.7 on 2020-11-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0033_auto_20201126_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradehistory',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='securityportfolios',
            name='total_cost_in_rub',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=17),
        ),
    ]
