# Generated by Django 3.0.7 on 2020-11-29 18:11

from django.db import migrations
from decimal import Decimal
from ..models import SecurityPortfolios,Security

def refresh_total_cost_in_rub(apps, schema_editor):
    s_p = SecurityPortfolios.objects.\
        select_related('security').\
            select_related('portfolio').\
            all()
    for i in s_p:
        if i.security.main_board_faceunit != 'SUR':
            valute = Security.objects.filter(
                shortname=i.security.main_board_faceunit
            ).get()
            i.total_cost_in_rub = Decimal(
                i.total_cost) * Decimal(valute.today_price)
        else:
            i.total_cost_in_rub = i.total_cost
        i.save(update_fields=['total_cost_in_rub'])
        i.portfolio.refresh_portfolio()

class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0034_auto_20201129_1819'),
    ]

    operations = [
        migrations.RunPython(refresh_total_cost_in_rub),
    ]
