# Generated by Django 3.0.7 on 2020-12-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0035_auto_20201129_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='source',
            field=models.CharField(choices=[('rshb', 'РСХБ'), ('moex', 'МосБиржа'), ('yfinance', 'YFinance')], default='moex', max_length=20),
        ),
        migrations.AddField(
            model_name='security',
            name='website',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
