# Generated by Django 3.0.7 on 2020-12-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0036_auto_20201202_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='security',
            name='source',
            field=models.CharField(choices=[('rshb', 'РСХБ'), ('moex', 'МосБиржа'), ('yfinance', 'YFinance'), ('cbr', 'Центробанк')], default='moex', max_length=20),
        ),
    ]
