# Generated by Django 3.0.7 on 2020-12-02 20:19

from django.db import migrations

from ..models import Security

def refill_source_in_security(apps, schema_editor):
    for i in Security.objects.all():
        if i.security_type == 'pif_rshb':
            i.source = 'rshb'
        elif i.security_type == 'currency':
            i.source = 'cbr'
        i.save(update_fields=['source'])

class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0037_auto_20201202_2259'),
    ]

    operations = [
        migrations.RunPython(refill_source_in_security),
    ]
