# Generated by Django 3.0.7 on 2021-01-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0038_auto_20201202_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='issuesize',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=25),
        ),
    ]
