# Generated by Django 3.0.7 on 2021-04-21 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0039_security_issuesize'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSearchSecurity',
            fields=[
                ('security_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='moex.Security')),
            ],
            bases=('moex.security',),
        ),
    ]
