# Generated by Django 3.0.7 on 2021-04-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20210102_2321'),
        ('moex', '0040_newsearchsecurity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewSearchSecurity',
        ),
    ]
