# Generated by Django 3.0.7 on 2021-04-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0040_auto_20210427_2212'),
        ('moex', '0041_delete_newsearchsecurity'),
    ]

    operations = [
    ]
