# Generated by Django 3.0.7 on 2021-11-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0042_merge_20210427_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityportfolios',
            name='custom_currency',
            field=models.CharField(blank=True, choices=[('SUR', 'РУБ'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CNY', 'CNY')], default='SUR', max_length=20, null=True, verbose_name='Валюта пользователя'),
        ),
    ]
