# Generated by Django 3.0.5 on 2020-05-15 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invest_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('today_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ostatok', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('percent_profit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('year_percent_profit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VkladInvestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('popolnenie', models.BooleanField(default=True)),
                ('vklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vklad.UserVklad')),
            ],
            options={
                'ordering': ['-date', 'cash'],
            },
        ),
        migrations.CreateModel(
            name='VkladHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('percent_profit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('year_percent_profit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vklad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vklad.UserVklad')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
