# Generated by Django 3.0.5 on 2020-05-15 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vklad', '0002_auto_20200515_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservklad',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vklad', to=settings.AUTH_USER_MODEL),
        ),
    ]
