# Generated by Django 3.0.5 on 2020-10-27 08:43

from django.db import migrations
from django.contrib.auth import get_user_model
from ..models import UserInformer

def create_user_informers(apps, schema_editor):
    #create model instances for earlier created users
    User = get_user_model()
    for user in User.objects.all():
        UserInformer.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('informer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_user_informers),
    ]
