# Generated by Django 3.0.5 on 2020-06-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20200529_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfriendsrequests',
            options={'ordering': ['-new', '-created']},
        ),
    ]
