# Generated by Django 3.0.5 on 2020-10-29 18:42

import breports.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('breports', '0001_initial'), ('breports', '0002_auto_20201029_2059'), ('breports', '0003_auto_20201029_2107'), ('breports', '0004_auto_20201029_2121')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/app/bonds'), upload_to=breports.models.user_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breports', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
    ]
