# Generated by Django 3.0.5 on 2020-08-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_private_policy',
            field=models.BooleanField(default=False),
        ),
    ]
