# Generated by Django 3.0.5 on 2020-08-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_accept_private_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accept_private_policy',
            field=models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальных данных'),
        ),
    ]
