# Generated by Django 3.0.5 on 2020-08-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200831_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accept_private_policy',
            field=models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности'),
        ),
    ]
