# Generated by Django 3.0.5 on 2020-05-14 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('invest_cash', models.PositiveIntegerField()),
                ('today_cash', models.PositiveIntegerField()),
                ('percent_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year_percent_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('private', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=250)),
                ('strategia', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_likes', models.PositiveIntegerField(db_index=True, default=0)),
                ('total_followers', models.PositiveIntegerField(db_index=True, default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
                ('users_follows', models.ManyToManyField(blank=True, related_name='portfolio_followed', to=settings.AUTH_USER_MODEL)),
                ('users_like', models.ManyToManyField(blank=True, related_name='portfolio_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('percent_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year_percent_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.InvestmentPortfolio')),
            ],
        ),
    ]
