# Generated by Django 3.0.5 on 2020-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliohistory',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='percent_profit',
        ),
        migrations.RemoveField(
            model_name='portfoliohistory',
            name='year_percent_profit',
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='invest_cash',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='percent_profit',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='today_cash',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='year_percent_profit',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
