# Generated by Django 3.0.5 on 2020-05-14 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200514_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentportfolio',
            name='percent_profit',
        ),
        migrations.AddField(
            model_name='investmentportfolio',
            name='ostatok',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PortfolioInvestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('popolnenie', models.BooleanField(default=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.InvestmentPortfolio')),
            ],
        ),
    ]
