# Generated by Django 3.0.5 on 2020-05-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200514_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentportfolio',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='invest_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='ostatok',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='strategia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='today_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='total_followers',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='year_percent_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
