# Generated by Django 3.0.5 on 2020-05-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200514_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentportfolio',
            name='invest_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='ostatok',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='today_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='year_percent_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
