# Generated by Django 3.0.5 on 2020-05-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_investmentportfolio_percent_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliohistory',
            name='percent_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='portfoliohistory',
            name='year_percent_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='portfolioinvesthistory',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
