# Generated by Django 3.0.5 on 2020-05-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200514_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioinvesthistory',
            options={'ordering': ['-date', 'cash']},
        ),
    ]
