# Generated by Django 3.0.5 on 2020-05-15 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200515_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioinvesthistory',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_invests', to='portfolio.InvestmentPortfolio'),
        ),
    ]
