# Generated by Django 3.0.5 on 2020-05-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200515_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioinvesthistory',
            name='popolnenie',
        ),
        migrations.AddField(
            model_name='portfolioinvesthistory',
            name='action',
            field=models.CharField(default='vklad_to_portfolio', max_length=20),
        ),
    ]
