# Generated by Django 3.0.5 on 2020-05-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200515_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentportfolio',
            name='private',
            field=models.CharField(choices=[('da', 'deny_all'), ('af', 'allow_friends'), ('al', 'allow_login'), ('aa', 'allow_all')], default='da', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolioinvesthistory',
            name='action',
            field=models.CharField(choices=[('vp', 'vklad_to_portfolio'), ('pv', 'portfolio_to_vklad'), ('tp', 'take_profit')], default='vklad_to_portfolio', max_length=20),
        ),
    ]
