# Generated by Django 3.0.5 on 2020-06-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20200527_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentportfolio',
            name='manual',
            field=models.BooleanField(default=True),
        ),
    ]
