# Generated by Django 3.0.5 on 2020-07-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_investmentportfolio_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioinvesthistory',
            name='action',
            field=models.CharField(choices=[('vp', 'На портфель'), ('pv', 'На вклад'), ('tp', 'Доход'), ('br', 'Частичное погашение облигаций')], default='vklad_to_portfolio', max_length=20),
        ),
    ]
