# Generated by Django 3.0.5 on 2020-07-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20200714_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinvesthistory',
            name='ndfl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
