# Generated by Django 3.0.5 on 2020-07-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0024_tradehistory_ndfl'),
        ('portfolio', '0016_auto_20200716_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinvesthistory',
            name='security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moex.Security'),
        ),
    ]
