# Generated by Django 3.0.5 on 2020-08-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_portfolioinvesthistory_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentportfolio',
            name='change_percent_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='investmentportfolio',
            name='change_year_percent_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
