# Generated by Django 3.0.5 on 2020-08-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20200806_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentportfolio',
            name='change_today_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='investmentportfolio',
            name='previos_percent_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='investmentportfolio',
            name='previos_today_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investmentportfolio',
            name='previos_year_percent_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
