# Generated by Django 3.0.7 on 2020-12-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20201007_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinvesthistory',
            name='currency',
            field=models.CharField(blank=True, choices=[('SUR', 'РУБ'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CNY', 'CNY')], default='SUR', max_length=20, null=True),
        ),
    ]
