# Generated by Django 3.0.7 on 2020-12-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_portfolioinvesthistory_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioinvesthistory',
            name='cash_in_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
